### ISSUE TITLE
Class Cast Exception while accessing Map Fields in a DynamicMessage protobuf argument

### ISSUE THREAD

**Issue by alexells-stripe** [projectnessie/cel-java#211]
Hello! Recently I've run into an interesting error and I think it might be a problem in how CEL-Java processes `DynamicMessage` protobuf types that use a map field. I've encountered this error in the enterprise code base that I normally work in, and have pulled out a "minimal" repro that should illustrate the point.

When I run a CEL expression which accesses a map field on a Dynamically parsed protobuf type, I seem to receive a class cast exception: 
```
java.lang.ClassCastException: class com.google.protobuf.DynamicMessage cannot be cast to class com.google.protobuf.MapEntry (com.google.protobuf.DynamicMessage and com.google.protobuf.MapEntry are in unnamed module of loader 'app')
```

Meanwhile, performing the same operation by parsing a byte string into generated code, and then feeding that into my CelExpression works fine (see "event2" in my repro code). 

 From inspecting the parsed object, it appears that using the generated code parser will compile the byte string into a MapField object during parsing, while the DynamicMessage parser will simply leave the MapEntry's as a list of DynamicMessages. It seems that this list of MapEntry's is perhaps what CEL is throwing the exception about, but that is speculation.

The protobuf I'm using for my simple repro is something like:
```proto
syntax = "proto3";

message EventA {
  bool property_bool = 5;
  map<string, string> map_str = 11;
}
```

While my code looks like:
```java
// imports...
public class Main {

    public static void main(String[] args) throws InvalidProtocolBufferException, ScriptException {
        Examples.EventA generatedEventA = Examples.EventA.getDefaultInstance().toBuilder().setPropertyBool(true).putMapStr("key", "value").putMapStr("key2", "value2").build();

        Descriptors.Descriptor descriptor = Examples.EventA.getDescriptor();
        DynamicMessage dynamicType = DynamicMessage.newBuilder(descriptor).build();

        // Referencing the map in the event created by the generated code parser, will go just fine.
        String workingExpression = "event.property_bool == true && event2.map_str['key'] == 'value'";

        // Referencing the map in the dynamically parsed event will fail with an exception.
        String failingExpression = "event.property_bool == true && event.map_str['key'] == 'value'";

        ScriptHost.ScriptBuilder scriptBuilder = ScriptHost.newBuilder().build().buildScript(failingExpression);
        scriptBuilder.withTypes(dynamicType.getDefaultInstanceForType());
        scriptBuilder.withDeclarations(
            Decls.newVar("event", Decls.newObjectType(dynamicType.getDescriptorForType().getFullName())),
            Decls.newVar("event2", Decls.newObjectType(Examples.EventA.getDescriptor().getFullName()))
            );
        Script script = scriptBuilder.build();

        DynamicMessage dynamicEventA = dynamicType.getParserForType().parseFrom(generatedEventA.toByteString());
        Examples.EventA parsedUsingGeneratedCodeEvent = Examples.EventA.parseFrom(generatedEventA.toByteString());

        // Here we pass the same event twice, once where it is parsed dynamically using the descriptor + DynamicMessage,
        // and again where we simply pass in the original event.
        Boolean result = script.execute(Boolean.class, Map.of("event", dynamicEventA, "event2", parsedUsingGeneratedCodeEvent));
        System.out.println(result);
    }
}
```

The full exception stack trace I get while running this code is: 
```
Exception in thread "main" org.projectnessie.cel.tools.ScriptExecutionException: java.lang.ClassCastException: class com.google.protobuf.DynamicMessage cannot be cast to class com.google.protobuf.MapEntry (com.google.protobuf.DynamicMessage and com.google.protobuf.MapEntry are in unnamed module of loader 'app')
	at org.projectnessie.cel.tools.Script.execute(Script.java:49)
	at com.company.Main.main(Main.java:32)
Caused by: java.lang.ClassCastException: class com.google.protobuf.DynamicMessage cannot be cast to class com.google.protobuf.MapEntry (com.google.protobuf.DynamicMessage and com.google.protobuf.MapEntry are in unnamed module of loader 'app')
	at org.projectnessie.cel.common.types.pb.FieldDescription.getValueFromField(FieldDescription.java:471)
	at org.projectnessie.cel.common.types.pb.FieldDescription.getField(FieldDescription.java:438)
	at org.projectnessie.cel.common.types.pb.PbObjectT.get(PbObjectT.java:77)
	at org.projectnessie.cel.interpreter.AttributeFactory.refResolve(AttributeFactory.java:1222)
	at org.projectnessie.cel.interpreter.AttributeFactory$StringQualifier.qualify(AttributeFactory.java:840)
	at org.projectnessie.cel.interpreter.AttributeFactory$AbsoluteAttribute.tryResolve(AttributeFactory.java:363)
	at org.projectnessie.cel.interpreter.AttributeFactory$MaybeAttribute.resolve(AttributeFactory.java:612)
	at org.projectnessie.cel.interpreter.Interpretable$EvalAttr.eval(Interpretable.java:1698)

	at org.projectnessie.cel.interpreter.Interpretable$EvalEq.eval(Interpretable.java:395)
	at org.projectnessie.cel.interpreter.Interpretable$EvalAnd.eval(Interpretable.java:343)
	at org.projectnessie.cel.Prog.eval(Prog.java:89)
	at org.projectnessie.cel.tools.Script.execute(Script.java:43)
	... 1 more
```

I've attached a zip of my IntelliJ project with the above example in case that is helpful.
[cel-repro.tar.gz](https://github.com/projectnessie/cel-java/files/8895279/cel-repro.tar.gz)

**Comment by snazy** [comment]
Thanks for the detailed reproducer! Was pretty easy to get it fixed with this.

**Comment by alexells-stripe** [comment]
Thanks so much for the fix! We'll pull the latest version of cel-java and confirm1
